FROM node:8 as react-build
WORKDIR /app
COPY . ./
# Error on line 5
RUN npm run watch

FROM nginx:alpine
COPY — from=react-build /app/build /usr/share/nginx/html/
EXPOSE 80
CMD [“nginx”, “-g”, “daemon off;”]